### ISSUE TITLE
Error: error executing "/tmp/terraform_1830723312.sh": Process exited with status 126

### ISSUE THREAD

**Issue by sambit15k** [mithunshanbhag/meetup-azureblr-08242019#1]
Hi Mithun,
I am trying to apply this deployment & i am getting error as follows 
`    }

  # module.azureblr_demo_vnet.azurerm_resource_group.vnet will be created
  + resource "azurerm_resource_group" "vnet" {
      + id       = (known after apply)
      + location = "southindia"
      + name     = "azureblr-demo-rg3"
      + tags     = (known after apply)
    }

  # module.azureblr_demo_vnet.azurerm_subnet.subnet[0] will be created
  + resource "azurerm_subnet" "subnet" {
      + address_prefix       = "10.0.0.0/24"
      + id                   = (known after apply)
      + ip_configurations    = (known after apply)
      + name                 = "default"
      + resource_group_name  = "azureblr-demo-rg3"
      + virtual_network_name = "azureblr-demo-vnet3"
    }

  # module.azureblr_demo_vnet.azurerm_virtual_network.vnet will be created
  + resource "azurerm_virtual_network" "vnet" {
      + address_space       = [
          + "10.0.0.0/16",
        ]
      + dns_servers         = []
      + id                  = (known after apply)
      + location            = "southindia"
      + name                = "azureblr-demo-vnet3"
      + resource_group_name = "azureblr-demo-rg3"
      + tags                = {
          + "environment" = "testing"
        }

      + subnet {
          + address_prefix = (known after apply)
          + id             = (known after apply)
          + name           = (known after apply)
          + security_group = (known after apply)
        }
    }

Plan: 12 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

tls_private_key.id_rsa: Creating...
tls_private_key.id_rsa: Creation complete after 1s [id=6429b8d9e32062ded5a2eb0fd204dbf3fc32711d]
local_file.id_rsa: Creating...
local_file.id_rsa: Provisioning with 'local-exec'...
local_file.id_rsa (local-exec): Executing: ["cmd" "/C" "chmod 700 ./demo_rsa"]
local_file.id_rsa: Creation complete after 1s [id=9043bf410fffabbc7c83f529474b40c57b74ceb8]
azurerm_resource_group.azureblr_demo_rg: Creating...
azurerm_resource_group.azureblr_demo_rg: Creation complete after 3s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3]
module.azureblr_demo_vnet.azurerm_resource_group.vnet: Creating...
azurerm_public_ip.azureblr_demo_public_ip: Creating...
azurerm_network_security_group.azureblr_demo_nsg: Creating...
module.azureblr_demo_vnet.azurerm_resource_group.vnet: Creation complete after 0s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3]
module.azureblr_demo_vnet.azurerm_virtual_network.vnet: Creating...
azurerm_network_security_group.azureblr_demo_nsg: Creation complete after 1s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3/providers/Microsoft.Network/networkSecurityGroups/azureblr-demo-nsg]
providers/Microsoft.Network/publicIPAddresses/azureblr-demo-public-ip]
module.azureblr_demo_vnet.azurerm_virtual_network.vnet: Still creating... [10s elapsed]
module.azureblr_demo_vnet.azurerm_virtual_network.vnet: Creation complete after 11s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3/providers/Microsoft.Network/virtualNetworks/azureblr-demo-vnet3]
module.azureblr_demo_vnet.azurerm_subnet.subnet[0]: Creating...
module.azureblr_demo_vnet.azurerm_subnet.subnet[0]: Creation complete after 2s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3/providers/Microsoft.Network/virtualNetworks/azureblr-demo-vnet3/subnets/default]
azurerm_network_interface.azureblr_demo_network_interface: Creating...
azurerm_network_interface.azureblr_demo_network_interface: Creation complete after 1s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3/providers/Microsoft.Network/networkInterfaces/azureblr-demo-network-interface]
azurerm_virtual_machine.azureblr_demo_vm: Creating...
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [10s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [20s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [30s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [40s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [50s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [1m0s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [1m10s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [1m20s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Still creating... [1m30s elapsed]
azurerm_virtual_machine.azureblr_demo_vm: Creation complete after 1m33s [id=/subscriptions/0c92af80-b6bf-43e7-b207-f1082771249c/resourceGroups/azureblr-demo-rg3/providers/Microsoft.Compute/virtualMachines/azureblr-demo-vm]
null_resource.installation_mariadb: Creating...
null_resource.installation_mariadb: Provisioning with 'remote-exec'...
null_resource.installation_mariadb (remote-exec): Connecting to remote host via SSH...
null_resource.installation_mariadb (remote-exec):   Host: 20.44.34.105
null_resource.installation_mariadb (remote-exec):   User: localadmin
null_resource.installation_mariadb (remote-exec):   Password: false
null_resource.installation_mariadb (remote-exec):   Private key: true
null_resource.installation_mariadb (remote-exec):   Certificate: false
null_resource.installation_mariadb (remote-exec):   SSH Agent: false
null_resource.installation_mariadb (remote-exec):   Checking Host Key: false
null_resource.installation_mariadb (remote-exec): Connected!
null_resource.installation_mariadb (remote-exec): bash: /tmp/terraform_1830723312.sh: /bin/bash^M: bad interpreter: No such file or directory
Error: error executing "/tmp/terraform_1830723312.sh": Process exited with status 126`

Please guide me with the error

**Comment by mithunshanbhag** [comment]
Hi @sambit15k, thanks for raising this issue.  

From the logs, I'm assuming that you're running this either on linux or on mac (or WSL on windows). Is this correct? 

Can you please ensure that line endings for all files in the `demo-vm` folder are LF?  See screenshot below.  

Please let me know if you're still seeing this error after changing all files to LF. 

![image](https://user-images.githubusercontent.com/2327905/63748498-1c476980-c8c7-11e9-8bf8-8abdde68ff43.png)

**Comment by sambit15k** [comment]
Hi @mithunshanbhag , sorry for the delayed response as i was out for few days , 
So i have changed all files to LF like you said & vola its working ..
![image](https://user-images.githubusercontent.com/19977065/65130922-fe7ba900-da1b-11e9-8394-3834983e716c.png)
![image](https://user-images.githubusercontent.com/19977065/65132274-53b8ba00-da1e-11e9-8710-910b09f847fd.png)
![image](https://user-images.githubusercontent.com/19977065/65132308-629f6c80-da1e-11e9-8f2c-7caf1837fd93.png)

Thanks for the support .

**Comment by sambit15k** [comment]
closing the issue as this issue is fixed by changing the end of line sequence from CRLF to LF .

**Comment by mithunshanbhag** [comment]
Glad to know this is resolved. Happy terraforming!
